name: CI - Test Unitaires

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurer les dépendances du projet
        run: dotnet restore

      - name: Build du projet
        run: dotnet build --configuration Release

      - name: Exécuter les tests unitaires
        run: dotnet test ./TestTDD/TestTDD.csproj --configuration Release
